### ISSUE TITLE
Integrate Travis CI build

### ISSUE THREAD

**Issue by peter279k** [phootwork/xml#1]
As title, I think we can consider integrating Travis CI build service on this `xml` project.

**Comment by gossi** [comment]
In general yes, absolutely (though, this package has also no official release yet). Second please see the discussion in phootwork/lang#5 to merge those package into one repo, which is kinda the cause for this package to have no release. It makes more sense to wait for the merge and then plug in CI.

**Comment by cristianoc72** [comment]
Integration done in `phootwork/phootwork` monorepo.
